In [1]:
import nltk

In [3]:
text=" i like to read machnine learning algorithm"

In [ ]:
LookUp Error
>>> import nltk
>>> nltk.download('punkt_tab')


In [ ]:
corpus
documents
tokens

In [4]:
from nltk.tokenize import word_tokenize
word_tokenize(text)

['i', 'like', 'to', 'read', 'machnine', 'learning', 'algorithm']

In [6]:
corpus=''' hello  welcome to Rag training .
lets learn NLP , then LLM, Chaining
Oracle 23ai, prompting '''

In [5]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize

In [7]:
print(sent_tokenize(corpus))

[' hello  welcome to Rag training .', 'lets learn NLP , then LLM, Chaining\nOracle 23ai, prompting']


In [8]:
msg="Hell0 Arun, how are you?. ok. Iam doing well. hos is activities's code "

In [9]:
word_tokenize(msg)

['Hell0',
 'Arun',
 ',',
 'how',
 'are',
 'you',
 '?',
 '.',
 'ok.',
 'Iam',
 'doing',
 'well',
 '.',
 'hos',
 'is',
 'activities',
 "'s",
 'code']

In [10]:
from nltk.tokenize import wordpunct_tokenize
wordpunct_tokenize(msg)|-

['Hell0',
 'Arun',
 ',',
 'how',
 'are',
 'you',
 '?.',
 'ok',
 '.',
 'Iam',
 'doing',
 'well',
 '.',
 'hos',
 'is',
 'activities',
 "'",
 's',
 'code']

In [ ]:
TreebankTokenizer
|
class
 |- handles apostrophies
|- split punctuation
|- adds space 

can't --> "ca"  + "n't"

In [11]:
from nltk.tokenize import wordpunct_tokenize
print(wordpunct_tokenize)

<bound method RegexpTokenizer.tokenize of WordPunctTokenizer(pattern='\\w+|[^\\w\\s]+', gaps=False, discard_empty=True, flags=re.UNICODE|re.MULTILINE|re.DOTALL)>


In [12]:
from nltk.tokenize import TreebankWordTokenizer
print(TreebankWordTokenizer)

<class 'nltk.tokenize.treebank.TreebankWordTokenizer'>


In [ ]:
nltk
|----tokenize
       |-------treebank.py
                    |
                    class TreeBankTokenizer:
                                    def tokenize(self. ):
                                         ..

In [13]:
msg

"Hell0 Arun, how are you?. ok. Iam doing well. hos is activities's code "

In [15]:
msg="Hell0 Arun, how are you?. ok. Iam doing well. how is activities's code  ab's data1.c"
from nltk.tokenize import TreebankWordTokenizer
obj=TreebankWordTokenizer()
obj.tokenize(msg)

['Hell0',
 'Arun',
 ',',
 'how',
 'are',
 'you',
 '?',
 '.',
 'ok.',
 'Iam',
 'doing',
 'well.',
 'how',
 'is',
 'activities',
 "'s",
 'code',
 'ab',
 "'s",
 'data1.c']

In [16]:
# nlp term
# Stemming - reduce to the root words

from nltk.stem import PorterStemmer
obj=PorterStemmer()
obj.stem("learning")

'learn'

In [17]:
obj.stem('history')

'histori'

In [18]:
obj.stem('congratulations')

'congratul'

In [19]:
from nltk.stem import RegexpStemmer
reg_stem = RegexpStemmer('ing$|s$|es$') # user specific regx pattern
reg_stem.stem('eating')

'eat'

In [20]:
reg_stem.stem('history')

'history'

In [ ]:
# Lemmatization - Lemma
# reducing to root word based pos = v,av,n

In [21]:
from nltk.stem import WordNetLemmatizer
lemma_obj=WordNetLemmatizer()
lemma_obj.lemmatize("eating")

'eating'

In [22]:
lemma_obj.lemmatize("eating", pos='v')

'eat'

In [23]:
lemma_obj.lemmatize("history", pos='v')

'history'

In [ ]:
StopWords - NLP reprocessing
 |------> do not carry any meaning


In [25]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\karth\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [55]:
stopwords.words('english')
#stopwords.words('arabic')
#stopwords.words('french')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
tokenization---> token - reduce this token to root word- stem-> lemma -> stopwords

In [30]:
Gn_list=["words","eats","eatern","writing",
         "writes","programming","program",
         "history","finally","finalized"]
# import nltk module
  #         |-- porterStemmer  - root words
  #      |--- WordNetLemmatizer - pos = v

In [31]:
Gn_list=["words","eats","eatern","writing",
         "writes","programming","program",
         "history","finally","finalized"]
obj=PorterStemmer()
for var in Gn_list:
    print(f'{var} ----->  {obj.stem(var)}')

words ----->  word
eats ----->  eat
eatern ----->  eatern
writing ----->  write
writes ----->  write
programming ----->  program
program ----->  program
history ----->  histori
finally ----->  final
finalized ----->  final


In [32]:
lemma_obj = WordNetLemmatizer()
for var in Gn_list:
    print(f"{var}----> { lemma_obj.lemmatize(var,pos='v')}")

words----> word
eats----> eat
eatern----> eatern
writing----> write
writes----> write
programming----> program
program----> program
history----> history
finally----> finally
finalized----> finalize


In [36]:
msg="This is an example displaying of list or collection of stop words to filter"
print(msg)

This is an example displaying of list or collection of stop words to filter


In [37]:
word_tokenize(msg)

['This',
 'is',
 'an',
 'example',
 'displaying',
 'of',
 'list',
 'or',
 'collection',
 'of',
 'stop',
 'words',
 'to',
 'filter']

In [38]:
words=word_tokenize(msg)
for var in words:
    if var.lower() not in stopwords.words('english'):
        print(var)

example
displaying
list
collection
stop
words
filter


In [39]:
filter_words= [var for var in words if var.lower() not in stopwords.words('english')]  # Functional Style- List comprehension
filter_words

['example', 'displaying', 'list', 'collection', 'stop', 'words', 'filter']

In [ ]:
#Task
#====
Corpus
|--- Use PorterStemmer  and WordNetLemmatizer()
|--- Apply StopWords
|--- Filter remaining words

In [40]:
corpus="""Vikram Sarabhai was born on 12 August 1919 in a Gujarati Śvetāmbara Shrimali Jain family, 
in Ahmedabad, India.His father was Ambalal Sarabhai,
a major industrialist committed to the Indian independence movement.
Known as the cradle of space sciences in India, the Physical Research Laboratory (PRL) was
founded in 1947 by Vikram Sarabhai. PRL had a modest beginning at his residence, the "RETREAT", 
with research on cosmic rays.
The institute was formally established at the M.G. Science Institute, Ahmedabad, on 11 November 1947 with support 
from the Karmkshetra Educational Foundation and the Ahmedabad Education Society. Kalpathi Ramakrishna Ramanathan 
was the first director of the institute. The initial focus was research on cosmic rays and the properties of the
upper atmosphere. Research areas were expanded to include theoretical physics and radio physics later
with grants from the Atomic Energy Commission. 
He led the Sarabhai family-owned business conglomerate."""

In [44]:
docs= sent_tokenize(corpus)
print(type(docs), len(docs))
for var in docs:
    print(var)

<class 'list'> 9
Vikram Sarabhai was born on 12 August 1919 in a Gujarati Śvetāmbara Shrimali Jain family, 
in Ahmedabad, India.His father was Ambalal Sarabhai,
a major industrialist committed to the Indian independence movement.
Known as the cradle of space sciences in India, the Physical Research Laboratory (PRL) was
founded in 1947 by Vikram Sarabhai.
PRL had a modest beginning at his residence, the "RETREAT", 
with research on cosmic rays.
The institute was formally established at the M.G.
Science Institute, Ahmedabad, on 11 November 1947 with support 
from the Karmkshetra Educational Foundation and the Ahmedabad Education Society.
Kalpathi Ramakrishna Ramanathan 
was the first director of the institute.
The initial focus was research on cosmic rays and the properties of the
upper atmosphere.
Research areas were expanded to include theoretical physics and radio physics later
with grants from the Atomic Energy Commission.
He led the Sarabhai family-owned business conglomerate.


In [45]:
for var in range(len(docs)):
    words= word_tokenize(docs[var])
    print(words)

['Vikram', 'Sarabhai', 'was', 'born', 'on', '12', 'August', '1919', 'in', 'a', 'Gujarati', 'Śvetāmbara', 'Shrimali', 'Jain', 'family', ',', 'in', 'Ahmedabad', ',', 'India.His', 'father', 'was', 'Ambalal', 'Sarabhai', ',', 'a', 'major', 'industrialist', 'committed', 'to', 'the', 'Indian', 'independence', 'movement', '.']
['Known', 'as', 'the', 'cradle', 'of', 'space', 'sciences', 'in', 'India', ',', 'the', 'Physical', 'Research', 'Laboratory', '(', 'PRL', ')', 'was', 'founded', 'in', '1947', 'by', 'Vikram', 'Sarabhai', '.']
['PRL', 'had', 'a', 'modest', 'beginning', 'at', 'his', 'residence', ',', 'the', '``', 'RETREAT', "''", ',', 'with', 'research', 'on', 'cosmic', 'rays', '.']
['The', 'institute', 'was', 'formally', 'established', 'at', 'the', 'M.G', '.']
['Science', 'Institute', ',', 'Ahmedabad', ',', 'on', '11', 'November', '1947', 'with', 'support', 'from', 'the', 'Karmkshetra', 'Educational', 'Foundation', 'and', 'the', 'Ahmedabad', 'Education', 'Society', '.']
['Kalpathi', 'Ramak

In [46]:
for var in range(len(docs)):
    words= word_tokenize(docs[var])
    for word in words:
        if word.lower() not in stopwords.words('english'):
            print(word.lower())

vikram
sarabhai
born
12
august
1919
gujarati
śvetāmbara
shrimali
jain
family
,
ahmedabad
,
india.his
father
ambalal
sarabhai
,
major
industrialist
committed
indian
independence
movement
.
known
cradle
space
sciences
india
,
physical
research
laboratory
(
prl
)
founded
1947
vikram
sarabhai
.
prl
modest
beginning
residence
,
``
retreat
''
,
research
cosmic
rays
.
institute
formally
established
m.g
.
science
institute
,
ahmedabad
,
11
november
1947
support
karmkshetra
educational
foundation
ahmedabad
education
society
.
kalpathi
ramakrishna
ramanathan
first
director
institute
.
initial
focus
research
cosmic
rays
properties
upper
atmosphere
.
research
areas
expanded
include
theoretical
physics
radio
physics
later
grants
atomic
energy
commission
.
led
sarabhai
family-owned
business
conglomerate
.


In [47]:
L=['data1','data2','data1','data1'] 
set(L)

{'data1', 'data2'}

In [48]:
list(set(L))

['data1', 'data2']

In [52]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

stem_obj=PorterStemmer()
docs= nltk.sent_tokenize(corpus)

for var in range(len(docs)):
    words=nltk.word_tokenize(docs[var])
    words= [stem_obj.stem(word)for word in words if word not in stopwords.words('english')]
    docs[var] =" ". join(words)

docs



['vikram sarabhai born 12 august 1919 gujarati śvetāmbara shrimali jain famili , ahmedabad , india.hi father ambal sarabhai , major industrialist commit indian independ movement .',
 'known cradl space scienc india , physic research laboratori ( prl ) found 1947 vikram sarabhai .',
 "prl modest begin resid , `` retreat '' , research cosmic ray .",
 'the institut formal establish m.g .',
 'scienc institut , ahmedabad , 11 novemb 1947 support karmkshetra educ foundat ahmedabad educ societi .',
 'kalpathi ramakrishna ramanathan first director institut .',
 'the initi focu research cosmic ray properti upper atmospher .',
 'research area expand includ theoret physic radio physic later grant atom energi commiss .',
 'he led sarabhai family-own busi conglomer .']

In [54]:
# use LEmmatization
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

lemmatizer=WordNetLemmatizer()
docs= nltk.sent_tokenize(corpus)

for var in range(len(docs)):
    words=nltk.word_tokenize(docs[var])
    words= [lemmatizer.lemmatize(word,pos="v")for word in words if word not in stopwords.words('english')]
    l=set(words)
    words=list(l)
    docs[var] =" ". join(words)

docs


[', bear major 12 . Sarabhai father Ambalal Shrimali Gujarati August Jain movement Indian Śvetāmbara independence commit family industrialist Ahmedabad India.His 1919 Vikram',
 'Sarabhai sciences space Research found Known 1947 Laboratory . Physical Vikram , ( ) PRL cradle India',
 "RETREAT `` research begin , '' residence cosmic ray modest PRL .",
 'The institute formally establish M.G .',
 'Educational 1947 support . Ahmedabad November Science Foundation Institute 11 , Society Karmkshetra Education',
 'Kalpathi institute director Ramakrishna Ramanathan first .',
 'research atmosphere upper focus The initial ray properties cosmic .',
 'Research physics theoretical include Energy areas radio later Commission grant Atomic . expand',
 'Sarabhai conglomerate business lead He family-owned .']

In [ ]:
ngram technique
===============
    An n-gram - continuous sequence of n items from a corpus

food good bad => after lemmatization and filting stopwords
n=3 => no. of unique

n=1
food --> 1 0 0 --> [1 0 0 ]
good --> 0 1 1  -> [0 1 0]
bad --> 0 0 1  ->  [ 0 0 1]


n=2
---
food good   ->  1 0
----------   
good bad    ---> 0 1

n=3
food good bad  -> 1
                  0

In [57]:
from nltk.util import ngrams


In [59]:
data="likes read nlp applications"
word_tokenize(data)

['likes', 'read', 'nlp', 'applications']

In [60]:
token= word_tokenize(data)
ngrams(token,1)  # unigram

<generator object ngrams at 0x000001EE457E9A40>

In [ ]:
>>> def f1():
...     return 10
...
>>> f1()
10
>>> def f2():
...     yield 10
...
>>> f2()
<generator object f2 at 0x0000014514D6C5F0>
>>> # function returns an iterator obj--> generator
>>>
>>> next(f2())
10
>>>
>>> for var in f2():
...     print(var)
...
10
>>> list(f2())
[10]
>>> def f3():
...     yield 10
...     yield [1,2,3]
...     yield 1,
...
>>> f3()
<generator object f3 at 0x0000014514D6DE00>
>>> next(f3())
10
>>> next(f3())
10
>>> next(f3())
10
>>> for var in f3():
...     print(var)
...
10
[1, 2, 3]
(1,)
>>> list(f3())
[10, [1, 2, 3], (1,)]
>>>

In [61]:
list(ngrams(token,1))

[('likes',), ('read',), ('nlp',), ('applications',)]

In [62]:
list(ngrams(token,2))

[('likes', 'read'), ('read', 'nlp'), ('nlp', 'applications')]

In [63]:
list(ngrams(token,3))

[('likes', 'read', 'nlp'), ('read', 'nlp', 'applications')]

In [64]:
list(ngrams(token,4))

[('likes', 'read', 'nlp', 'applications')]

In [65]:
list(ngrams(token,5))

[]

In [71]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data=['food', 'good', 'bad']

data= np.array(data).reshape(-1,1) # 2D

encoder_obj=OneHotEncoder(sparse_output=False)
one_hot=encoder_obj.fit_transform(data)
print(encoder_obj.categories_)
print('')
print(one_hot)


[array(['bad', 'food', 'good'], dtype='<U4')]

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [72]:
data=["he","widely","regards","father", "indian","space","program"]
data= np.array(data).reshape(-1,1) # 2D

encoder_obj=OneHotEncoder(sparse_output=False)
one_hot=encoder_obj.fit_transform(data)
print(encoder_obj.categories_)
print('')
print(one_hot)


[array(['father', 'he', 'indian', 'program', 'regards', 'space', 'widely'],
      dtype='<U7')]

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [ ]:
#try 
#pip install scikit-learn
#import sklearn.preprocessing

In [74]:
np.array([10,20,30]).dtype

dtype('int64')

In [75]:
np.array([10,20,30,30.0]).dtype

dtype('float64')

In [76]:
np.array([10,20,30,'data']).dtype

dtype('<U21')

In [80]:
arr=np.array([[10,20,30,40,50,60]])
arr.ndim

2

In [81]:
print(arr)

[[10 20 30 40 50 60]]


In [82]:
arr.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [83]:
from sklearn.feature_extraction.text import CountVectorizer

In [86]:
docs=["i likes nlp and i likes python", "python and nlp courses"]
cv=CountVectorizer()
bow= cv.fit_transform(docs) # bag of words
print(cv.get_feature_names_out())
print(bow.toarray())


['and' 'courses' 'likes' 'nlp' 'python']
[[1 0 2 1 1]
 [1 1 0 1 1]]


In [ ]:
TF- IDF
Term Frequency- Inverse Document Frequency

s1--> good boy
s2--> good girl
s3--> boy girl good

TF=no. of repeatation of a specific word
   -------------------------------------
    no. of words in sentence

IDF= log (    no. of sentence / no.of sentences containing word)

TF
===
        s1     s2    s3
good    1/2    1/2   1/3
boy     1/2    0/2   1/3
girl    0/2    1/2   1/3

IDF
===

words
good    log(3/3)
girl    log(3/2)
boy     log(3/2)

In [ ]:
Transformer - Encoder + Decoder

In [ ]:
LangChain
|------OpenSource Framework - genAI Appln
|
|
|---- use LLM
| ---- connect data with LLM

    Components
    ----------
    1. chain
    2. Prompt management
    3. Vector DB
    4. Model
    5. Memory
    6. Agent

    ex: explain about python -- Q1
    .....................................
    give me 5 features  --Q2
     ..............................

|---> community documents
    
    

In [ ]:
1. Data Loading from various sources - text file, pdf, web, wikipedia... // loader class
2. Split data into multiple chunks
3. using embedding model-- > chunks--> vectors
4. stores in vectorDB
5. similarity search
------------------------------------------//
6. llm
7. prompt
8. chain
9. outputparser
10.userinterface - streamlit, flask app

In [ ]:
C:\Users\karth>ollama --version
ollama version is 0.13.5

C:\Users\karth>ollama -V
Error: unknown shorthand flag: 'V' in -V

C:\Users\karth>ollama -v
ollama version is 0.13.5

C:\Users\karth>ollama list
NAME                       ID              SIZE      MODIFIED
gemma2:2b                  8ccf136fdd52    1.6 GB    19 hours ago
nomic-embed-text:latest    0a109f422b47    274 MB    19 hours ago

C:\Users\karth># ollama pull <modelname>   # To download model
The system cannot find the file specified.

C:\Users\karth># ollama run <modelname> # To run a model
The system cannot find the file specified.

C:\Users\karth>ollama list
NAME                       ID              SIZE      MODIFIED
gemma2:2b                  8ccf136fdd52    1.6 GB    19 hours ago
nomic-embed-text:latest    0a109f422b47    274 MB    19 hours ago

C:\Users\karth>ollama rm <modelname>
The syntax of the command is incorrect.

C:\Users\karth>ollama run gemma2:2b
>>> what is langchain?
LangChain is a powerful framework for building applications using large language models (LLMs).  Think of it like
a toolkit that helps developers combine LLMs with other data and tools to create more complex and versatile AI
experiences.

**Here's the lowdown:**

* **What it does:** LangChain streamlines the process of integrating LLMs into your applications, offering
features such as:
    * **Memory**:  Store information about previous interactions with your LLM for context and conversational flow
(like a chatbot!).
    * **Chains**: Create sequences of commands to achieve complex tasks. Think "summarize this article, then
generate different marketing copy based on the summary."
    * **Agents:** Build autonomous agents that can interact with various environments and make decisions based on
their understanding.
    * **Data Integration:** Connect your LLMs to external data sources like APIs, databases, and documents to
access relevant information for more accurate responses.

* **Who it's for:**  LangChain is a valuable tool for:
    * Developers who want to build powerful LLM applications like chatbots, question-answer systems, or text
summarizers.
    * Businesses looking to automate processes and improve efficiency with AI.
    * Researchers working on advanced AI models.

**Analogy:** Imagine you're writing a story (the LLM is your character). LangChain helps you give your story more
depth and purpose by:
 *  Creating a storyline based on different data points like plot twists or information from real life.
 *  Linking characters to specific environments for richer interactions.


**In a nutshell:** LangChain makes it easier to work with LLMs and build innovative applications powered by AI.

**To learn more, check out:**

* **

>>>

C:\Users\karth>ollama list
NAME                       ID              SIZE      MODIFIED
gemma2:2b                  8ccf136fdd52    1.6 GB    19 hours ago
nomic-embed-text:latest    0a109f422b47    274 MB    19 hours ago

C:\Users\karth>ollama run nomic-embed-text:latest
Error: embedding models require input text. Usage: ollama run nomic-embed-text:latest "your text here"

C:\Users\karth>ollama run nomic-embed-text:latest "hello"
[0.017860368,-0.005880318,-0.17529128,-0.013721276,0.03403859,0.044752814,0.012422824,-0.0025509228,-0.014760505,-0.03928757,-0.009200146,0.051717155,0.05771218,0.057226323,0.045014214,-0.05359758,0.028783012,-0.047195476,-0.039058723,0.026992228,0.009364105,-0.06674605,0.004949517,-0.0058987713,0.17222914,-0.004382981,0.01864732,0.083406255,0.0016174744,-0.02250796,0.02034864,-0.018761951,0.015323926,0.0032324812,0.02755448,-0.01871097,-0.0038496028,0.011239505,0.016208217,0.01929364,-0.01764852,-0.009595988,0.009243244,-0.02831918,0.05137727,0.007274074,-0.022126125,0.013326626,0.053705517,-0.043480553,-0.003986369,-0.00420693,-0.022152327,0.04244238,0.033516046,0.05497025,0.057901107,0.020405494,0.021781452,0.025755676,0.037800968,0.047367595,0.019435268,0.07026823,-0.0026357146,-0.032041043,-0.010766219,0.03776245,0.047613546,-0.004171873,0.07182922,0.0026584587,0.018865246,-0.0024502345,0.015050562,0.02064043,0.0057850573,-0.029026812,-0.024805265,-0.037957177,0.030283615,-0.061501738,0.073149055,-0.05746802,0.016398309,-0.031170418,-0.018681915,-0.00021392228,-0.052027125,0.0069116903,0.04949368,0.0063920305,-0.011707167,0.037248943,-0.038340807,0.005969399,-0.031469993,0.00048377286,-0.051756456,-0.056019537,-0.0056988457,0.019381372,-0.004601417,0.008907521,0.057604685,0.043122116,-0.036950637,-0.038359072,-0.037678033,-0.030469624,-0.053724006,0.023722827,-0.012083642,0.0045474246,0.0004580619,0.0046509188,0.03941937,-0.09525451,0.040553935,0.038455192,-0.071363114,0.01063518,0.0049926974,0.039715204,0.02650702,0.04915366,-0.090285555,-0.014988227,-0.004449548,0.010545871,0.006581031,-0.034487534,-0.009414395,-0.034195054,0.034734555,0.0096996445,-0.040370632,-0.02164169,0.03675973,0.009738772,0.020242564,0.018505812,0.023278851,-0.049513616,-0.035538286,-0.03042774,0.07503323,-0.04826561,0.017414741,-0.007243618,0.014306152,0.039287634,0.021788498,0.0038678648,0.026368232,-0.016929219,-0.012645982,0.00033233236,0.03874378,-0.03079375,0.010665363,-0.032959554,-0.047336094,0.007695892,-0.008897357,-0.058269072,0.0018215001,0.041220505,0.04596221,0.040155023,-0.012623088,-0.04596179,-0.01109474,-0.0026871243,-0.0032333403,0.004236132,-0.008210016,-0.06381824,0.024798958,-0.011827391,0.019828474,-0.058038324,0.028569378,0.031238642,-0.03819286,-0.02094438,0.002618026,0.01238333,-0.015436716,-0.02661699,-0.031351525,0.006939414,-0.059028044,-0.037714414,-0.011104786,-0.017169239,0.026147157,0.016324643,0.055456575,-0.030510584,-0.050826624,-0.012130352,-0.0041694613,0.0016681238,0.014953969,0.09705322,0.02925681,0.028252965,0.03444062,0.01890566,0.08541962,-0.061635673,-0.03431772,-0.019245988,-0.003208898,0.0019301319,0.02777815,-0.029603686,0.002282565,0.024885366,0.025125014,-0.040680807,0.021241548,-0.009766724,0.046550773,-0.023384215,-0.01427931,0.0000913809,-0.07296258,0.019429972,-0.055853125,-0.05012878,0.030918408,0.020453941,-0.0071502086,0.02185678,0.045257933,0.06415905,-0.008021594,-0.027324775,-0.029933115,0.047874913,0.040672354,0.0047284765,-0.06622185,0.025268964,-0.017620454,0.0075680357,0.0054270243,0.0049950797,-0.018857457,-0.009234486,-0.034252226,0.03152015,0.033934735,-0.042542856,-0.036943335,0.024518978,-0.024489524,-0.044251844,0.026629118,-0.09310856,0.018127864,-0.060437508,-0.0508711,0.017333586,-0.04829309,0.008386456,0.04344447,-0.034073085,0.0013360814,0.013198015,0.015223831,0.035051033,-0.031234741,-0.0001792367,0.0054944297,0.020193951,-0.041197915,-0.009368439,-0.018181663,-0.043087266,-0.05926647,-0.026738228,0.0050344523,0.04492033,0.022938237,0.02958477,-0.009887955,0.011340574,0.024117457,0.013106258,0.026926212,0.065281786,-0.02627884,0.002793322,0.028257102,0.017976902,-0.038332406,-0.0129609015,-0.022483079,0.046461392,0.054434273,-0.034493726,-0.0033156795,0.0044139246,0.030413,-0.023233037,0.056663495,0.018557344,-0.070695676,0.038192965,-0.06515675,-0.006850395,-0.039724577,0.025936488,-0.009006914,0.035830803,0.07508239,0.046541434,-0.021216422,-0.048905507,-0.006012207,-0.04947853,0.016443454,0.020270621,0.026076844,0.061514307,0.034111444,-0.027095636,0.023973402,0.011644986,-0.048252948,-0.027199566,-0.02832465,0.036500458,0.010683915,-0.0051506013,-0.026388157,0.07393915,0.021655383,-0.024513444,0.02419472,-0.02017595,-0.024184378,-0.038734443,-0.017109146,0.0026636356,-0.026333401,-0.0106397085,-0.018606879,0.04707917,-0.031181157,0.027668813,0.0133915935,-0.00034284923,0.03221943,0.039296664,0.01374417,-0.026111495,-0.0053435992,-0.012217772,0.035472665,-0.0061222934,-0.039127495,0.028643362,0.01404635,0.008591807,0.034330428,0.012886857,-0.04409949,-0.02330491,-0.0069598122,0.03441854,0.03888655,0.015615262,-0.084011115,-0.038742494,0.014238609,0.00751673,-0.013170077,-0.011105788,0.040688254,-0.03828955,0.03980857,0.048281536,0.038280964,0.0025481798,0.0041990476,0.008878313,-0.0013026483,-0.001331895,-0.015143568,0.015507365,-0.0119528035,-0.0022658708,0.045437068,0.011907441,-0.022507694,-0.004864644,-0.029614126,0.0024063191,0.0102991825,-0.08083363,0.006650415,0.0135130705,-0.031900633,-0.027494408,-0.0025165963,-0.02822683,0.05575717,0.0015283172,0.014701263,-0.043647543,-0.004215854,0.014708069,0.04395805,-0.04150607,-0.029946247,0.019263383,0.045574304,0.05060934,0.026141245,0.0016133827,-0.013278699,0.077146985,0.02009641,0.043369435,0.020181732,-0.06437711,-0.0071234875,0.0033943565,0.039469622,0.029090703,-0.033232905,-0.029116284,0.015271585,-0.016118359,0.0103869615,0.02288849,0.057662528,-0.0246532,-0.07397761,0.0021622127,0.03032581,0.117301,0.09918122,-0.035232686,-0.0642044,-0.015739717,0.013315119,0.021038763,0.018458819,0.006688024,0.08229004,-0.059372917,0.045015343,-0.0057618134,0.010266579,0.029558046,0.031448506,0.022635257,-0.016209606,0.0011044247,-0.004363984,-0.052405946,0.01135951,-0.008062068,0.0032934418,0.03564111,-0.060261127,-0.032563154,0.014903902,-0.027944176,-0.039704114,0.020810151,0.009385864,-0.01787266,0.0035187986,0.036082048,0.010764196,0.0113635445,-0.06660004,-0.020061133,0.015656631,0.048048824,-0.0005256818,0.03099477,0.011989968,0.021285718,0.026121616,0.0061695976,0.027883923,0.011993503,-0.006467747,-0.0103724,-0.062004033,0.035940234,-0.025783872,-0.016484525,0.0050060055,0.011853178,-0.009114532,0.023922246,0.0060655917,0.005141192,0.02898987,-0.07712731,-0.019418575,0.0059240474,-0.010793916,0.010919627,-0.0061062165,0.03880744,0.06345246,-0.042004537,0.031718977,-0.017401738,-0.044112615,0.0747718,-0.004649097,-0.0663012,0.0023077214,0.014370927,-0.08108808,0.05810594,-0.0098635405,-0.010505452,0.04310117,0.015184307,-0.0010166687,0.0018214029,-0.023633752,-0.051898807,-0.0012805666,-0.00909261,-0.019815547,0.03663618,0.0047921995,0.009491083,-0.054922212,0.020989453,-0.004306235,-0.01745168,0.03984779,0.033778317,-0.033686288,-0.011724957,0.024946703,-0.0035487674,-0.023116084,-0.056529507,-0.004255076,-0.041630194,-0.04097412,-0.07299581,-0.01594963,0.010920403,-0.026863143,-0.053734045,0.07538777,0.02826151,-0.000058346475,-0.008094224,0.032333046,-0.018395742,0.0063174576,-0.03530382,-0.0026941656,-0.021775596,-0.016231509,-0.05567346,0.051096987,-0.04112871,-0.0017323175,0.016996175,0.031434763,-0.0026465906,-0.07406271,-0.025550839,-0.0047113346,-0.014053704,-0.023840062,0.053761546,-0.009728622,0.01951716,0.0028435765,-0.052222647,0.054105416,-0.016960192,-0.006534154,0.0032998833,0.030624973,-0.026571628,-0.01745271,0.06300624,-0.010783237,-0.06170387,-0.018715609,-0.015941624,-0.02903186,0.002297035,0.06187133,-0.044788357,-0.010245513,0.076383874,0.037700344,0.044386957,0.006285001,-0.0061902553,0.062444326,0.03476711,-0.030283973,0.016273914,0.046589866,-0.015218305,-0.014543282,-0.013322764,0.01598687,-0.046202023,-0.032922745,-0.026151711,0.046480123,0.0102628,0.02552239,-0.024694202,-0.04055441,-0.04307006,-0.03344652,0.052090324,0.023056895,-0.04306217,-0.09566476,-0.014106147,0.0032079988,0.026800795,0.033734523,0.004543458,0.002738151,0.034778085,0.09816091,-0.011866037,0.03020925,0.011511038,0.047920268,-0.019795157,0.027167229,0.020326687,0.038437374,0.010024084,0.059958514,0.039668918,0.024629563,0.02159634,-0.0031092463,-0.02409649,0.01823242,-0.017688427,-0.08733394,0.022539994,-0.024013005,0.016363977,-0.09067748,-0.0679618,0.04147759,-0.012693609,-0.013115287,0.030227074,-0.07169155,-0.0053778253,-0.011092428,-0.028297486,-0.014734586,-0.03916293,-0.058031645,0.052158352,0.049460802,0.016630404,0.040639002,-0.00719335,-0.011894629,-0.014261786,-0.010812772,0.04620517,0.030914685,-0.06875327,0.05932612,0.0021244965,-0.05010033,-0.08525335,-0.0031635282,-0.053415418,-0.009147353,-0.0030396504,-0.036380604,-0.0014916657,-0.020501561,0.028144194,-0.032128256,0.051824983,-0.05831513,-0.010667104,0.004964954,0.02252253,-0.014235271,-0.013571326,-0.004053372,0.034637667,-0.041326713,-0.00037538842,-0.012151706,0.046991467,0.009692152,0.05944107,0.0105869565,0.004659791,-0.038019434,-0.002789343,-0.0077159847,0.06181793,0.08557673,0.017828688,-0.051017895,-0.022311732,-0.036231857,0.0005840571,0.022685673,-0.029610926,0.006322717,-0.03453666,-0.01342647,-0.018374298,-0.059802104,0.0456527,-0.016767176,0.0072272797,-0.00025763386,-0.075691685,-0.010423527,-0.011642503,-0.04580213,-0.070801035,-0.0017079357,0.09042611,-0.0010576012,-0.04610344,0.030724194,0.03259058,-0.021382995,-0.007199502,0.029605513,-0.0046130884,-0.016326057,-0.015416303,0.0285162,0.011845546,-0.007296305,0.04587301,0.05762016,-0.030737147,0.048767455,-0.010170026,0.015620471,0.026530715,0.0021643108,-0.014142397,-0.07688886,-0.019889472]


In [ ]:
pip install -r requirements.txt  
inside Jupyter
|
! pip install -r requirements.txt
    

In [88]:
from langchain_ollama import OllamaLLM


In [89]:
print(OllamaLLM)

<class 'langchain_ollama.llms.OllamaLLM'>


In [91]:
import langchain_ollama
langchain_ollama.__file__

'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\langchain_ollama\\__init__.py'

In [ ]:
langchain_ollama
          |--------llms.py
                    |-------class OllamaLLM:
                             ....

In [93]:
from langchain_ollama import OllamaLLM

llm_obj=OllamaLLM(model="gemma2:2b")
result= llm_obj.invoke("what is GenAI?")
print(type(result),len(result))


<class 'str'> 2214


In [94]:
print(result)

"GenAI" stands for **Generative Artificial Intelligence**. 

Essentially, it's a branch of artificial intelligence (AI) focused on **creating new content** rather than just analyzing or interpreting existing data.  Here's a breakdown:

**What does GenAI do?**

* **Generates text:**  Writing stories, poems, articles, even scripts.
* **Creates images and art:** Generating realistic paintings, sketches, photographs, and more.
* **Composes music:** Creating original melodies, harmonies, and rhythms. 
* **Develops videos:** Generating short films, animation clips, or even entire movie sequences. 
* **Powers virtual assistants:** Enabling them to understand and respond to complex requests naturally.

**Key Characteristics of GenAI:**

* **Creativity:**  Unlike traditional AI, GenAI models are designed to generate entirely new content based on their training data. 
* **Learning from Data:** They learn patterns and relationships within massive datasets to create outputs that resemble human cre

In [95]:
result1= llm_obj.invoke("How to write Hello world program in Python?")
print(result1)

```python
print("Hello, world!") 
```

**Explanation:**

* **`print()`:** This is a built-in function in Python that displays output on the console.
* **`"Hello, world!"`:** This is a string of text enclosed in double quotes (`"`). The `print()` function takes this string and outputs it to the screen.


**How to run this program:**

1. **Save the code:** Create a new file (e.g., hello.py) and paste the code into it.
2. **Open a terminal/command prompt:** Navigate to where you saved the file using the `cd` command.
3. **Run the script:** Type `python hello.py` and press Enter.

You should see "Hello, world!" printed on your screen.


Let me know if you'd like to explore more complex Python programs or learn about other ways to interact with the console! 


In [97]:
llm=OllamaLLM(model="llama")
#llm.invoke("what is AI?")
# ResponseError: model 'llama' not found (status code: 404)

ResponseError: model 'llama' not found (status code: 404)

In [ ]:
# Data Loading from various sources - text file, pdf, web, wikipedia... // loader class

document loading
-------->langchain_community.document_loaders
                                        |------> TextLoader  |---> PDFLoader    <classes>
1. using document loader class -> Get the doc
2. doc-->metadata+ actual data
                    ==========
                       |--> page_content:<actual_data>

In [98]:
from langchain_community.document_loaders import TextLoader
TextLoader('my_docs.txt')

In [99]:
loader_obj = TextLoader('my_docs.txt')   #  input file --> Reg. file/ ASCII/TextFile
loader_obj.load()  # --> doc


[Document(metadata={'source': 'my_docs.txt'}, page_content="LangChain is a framework for developing applications powered by large language models (LLMs).\n\nLangChain simplifies every stage of the LLM application lifecycle:\n\nDevelopment: Build your applications using LangChain's open-source components and third-party integrations. Use LangGraph to build stateful agents with first-class streaming and human-in-the-loop support.\nProductionization: Use LangSmith to inspect, monitor and evaluate your applications, so that you can continuously optimize and deploy with confidence.\nDeployment: Turn your LangGraph applications into production-ready APIs and Assistants with LangGraph Platform.")]

In [101]:
from langchain_community.document_loaders import TextLoader
loader_obj = TextLoader('my_docs.txt')  
Text_doc= loader_obj.load()  

from langchain_community.document_loaders import PyPDFLoader
loader_obj=PyPDFLoader('attention.pdf')
pdf_docs=loader_obj.load()

In [102]:
print(type(Text_doc), len(Text_doc))

<class 'list'> 1


In [103]:
print(type(pdf_docs),len(pdf_docs))

<class 'list'> 15


In [ ]:
#####################################

In [ ]:
requests - GET 
bs4 - extract data

In [ ]:
import requests
requests.get('url') ---> return status code --> 200 ; okay ; != 200  -> Failed

requests.get('url')--> returncode.headers-> {} -
                    |---> returncode.text ---> Get data

In [104]:
import requests
requests.get('http://www.google.com')

<Response [200]>

In [105]:
r= requests.get('http://www.google.com')
r.headers

{'Date': 'Mon, 12 Jan 2026 11:03:14 GMT', 'Expires': '-1', 'Cache-Control': 'private, max-age=0', 'Content-Type': 'text/html; charset=ISO-8859-1', 'Content-Security-Policy-Report-Only': "object-src 'none';base-uri 'self';script-src 'nonce-dWxb2iOZGz2akSZkm3qP5A' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp", 'P3P': 'CP="This is not a P3P policy! See g.co/p3phelp for more info."', 'Content-Encoding': 'gzip', 'Server': 'gws', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Set-Cookie': '__Secure-STRP=AD6DogsCESHFD5QgCtGpvFS80-iurTG88u6GWAqHmgKPabwdx3Y5FfTLxXnaNe5gGOpamAa6in7aa9WjrPRxEk-dNHYlO1o9z5Yo; expires=Mon, 12-Jan-2026 11:08:14 GMT; path=/; domain=.google.com; Secure; SameSite=strict, AEC=AaJma5vQuRpMqxyaywQzre6oUyVT0DTwqRlYFjS215nrButxzTOd3PRFdA; expires=Sat, 11-Jul-2026 11:03:14 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=528=B_jq_X4RTl-33C4hravo-tk4oyKgCpOhqu

In [106]:
r.text

'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-IN"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="dWxb2iOZGz2akSZkm3qP5A">(function(){var _g={kEI:\'8tRkabyzMer8kPIP34GliQ0\',kEXPI:\'0,203004,1101199,2949954,425602,270475,30675,5231286,257,36811675,25381059,65176,30628,9138,11153,50098,14067,15097,8157,3292,34513,28334,48904,30410,7714,33385,3050,2,875,7,25160,2884,19843,46337,21899,4372,6292,6437,9742,2646,103,4,1,13145,10993,14505,1198,185,2,1,1515,3355,2,194,5814,2,4205,3,10939,775,4384,2,874,24,1653,554,5089,19,3008,22,773,4081,4,5386,13783,2386,2,1,9730,211,1039,1034,4303,311,534,846,1200,2,12,16,415,1,1129,3,2842,9,27,8,3055,1010,1747,4,4636,10557,4,696,1475,45,2,9,4,12,241,296,5,1113,389,4,299,2264,84,5,5568,298,5201,1055,2997,1275,7,1784,7,997,46,2,296,1622,516,6032,1251,4,93,2,2559,2,5724,9,

In [107]:
google_web=r.text
print(type(google_web),len(google_web))

<class 'str'> 19706


In [108]:
## For testing
with open('test1.html','w') as wobj:
    wobj.write(google_web)

In [ ]:
import bs4
#  bs4
#   |
#  BeautifulSoup(webpagecontent)--> bs4_obj
# bs4_obj.find(<htmltag>) => single str
(or)
# bs4_obj.find_all(<html_tag>) => data_list

In [109]:
import bs4
web_obj=bs4.BeautifulSoup(google_web)
web_obj.title

<title>Google</title>

In [110]:
web_obj.find('title')   # same as web_obj.title

<title>Google</title>

In [111]:
web_obj.find_all('p')

[<p style="font-size:8pt;color:#636363">© 2026 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>]

In [115]:
web_obj.find('p').get('style')

'font-size:8pt;color:#636363'

In [116]:
web_obj.find('a').get('href')

'https://www.google.com/imghp?hl=en&tab=wi'

In [121]:
# List of URLs from google.com
# Listof rpm file from yum.oracle.com/OL9
r=requests.get('https://www.google.com')
webpage=r.text
gpage=bs4.BeautifulSoup(webpage)


In [120]:
L=gpage.find_all('a')
for var in L:
    print(var.get('href'))

https://www.google.com/imghp?hl=en&tab=wi
https://maps.google.co.in/maps?hl=en&tab=wl
https://play.google.com/?hl=en&tab=w8
https://www.youtube.com/?tab=w1
https://news.google.com/?tab=wn
https://mail.google.com/mail/?tab=wm
https://drive.google.com/?tab=wo
https://www.google.co.in/intl/en/about/products?tab=wh
http://www.google.co.in/history/optout?hl=en
/preferences?hl=en
https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/&ec=GAZAAQ
/advanced_search?hl=en-IN&authuser=0
https://www.google.com/setprefs?sig=0_XmMtEbfzA0YV2bnETHezwjmTKc4%3D&hl=hi&source=homepage&sa=X&ved=0ahUKEwjNsJmR8IWSAxVbEEQIHcVDAUIQ2ZgBCAY
https://www.google.com/setprefs?sig=0_XmMtEbfzA0YV2bnETHezwjmTKc4%3D&hl=bn&source=homepage&sa=X&ved=0ahUKEwjNsJmR8IWSAxVbEEQIHcVDAUIQ2ZgBCAc
https://www.google.com/setprefs?sig=0_XmMtEbfzA0YV2bnETHezwjmTKc4%3D&hl=te&source=homepage&sa=X&ved=0ahUKEwjNsJmR8IWSAxVbEEQIHcVDAUIQ2ZgBCAg
https://www.google.com/setprefs?sig=0_XmMtEbfzA0YV2bnETHezwj

In [ ]:
#############################################################################

In [123]:
from langchain_community.document_loaders import TextLoader
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.document_loaders import WebBaseLoader
# From Single URL
web_loader= WebBaseLoader(web_path='https://www.google.com')
web_loader.load()

[Document(metadata={'source': 'https://www.google.com', 'title': 'Google', 'language': 'en-IN'}, page_content='GoogleSearch Images Maps Play YouTube News Gmail Drive More »Web History | Settings | Sign in\xa0Advanced searchGoogle offered in:  हिन्दी বাংলা తెలుగు मराठी தமிழ் ગુજરાતી ಕನ್ನಡ മലയാളം ਪੰਜਾਬੀ AdvertisingBusiness SolutionsAbout GoogleGoogle.co.in© 2026 - Privacy - Terms')]

In [124]:
# From Multiple Web page
web_loader= WebBaseLoader(web_paths=['https://www.google.com','http://www.python.org'])
web_loader.load()

[Document(metadata={'source': 'https://www.google.com', 'title': 'Google', 'language': 'en-IN'}, page_content='GoogleSearch Images Maps Play YouTube News Gmail Drive More »Web History | Settings | Sign in\xa0Advanced searchGoogle offered in:  हिन्दी বাংলা తెలుగు मराठी தமிழ் ગુજરાતી ಕನ್ನಡ മലയാളം ਪੰਜਾਬੀ AdvertisingBusiness SolutionsAbout GoogleGoogle.co.in© 2026 - Privacy - Terms'),
 Document(metadata={'source': 'http://www.python.org', 'title': 'Welcome to Python.org', 'description': 'The official home of the Python Programming Language', 'language': 'en'}, page_content='\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWelcome to Python.org\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nNotice: While JavaScript is not essential for this website, your interaction with the content will be limited. Please turn JavaScript on for the full experience. \n\n\n\n\n\nSkip to content\n\n\n▼ Close\n                \n\n\nPython\n\n\nPSF\n\n\nDocs\n\n\nPyPI\n\n\nJobs\n\n\nCommunity\n\n\n\n▲ The Py

In [ ]:
WebBaseLoader(web_path='https://www.google.com')

VS

WebBaseLoader(web_path='https://www.google.com', bs_kwargs=dict(parse_only= bs4.SoupStrainer(class_=('TagName')))

              
WebBaseLoader(web_path='https://www.google.com', bs_kwargs=dict(parse_only= bs4.SoupStrainer(class_=('TagName, TagName2, TagNAme3')))


In [ ]:
URL= 'http://lilianweng.github.io/posts/2023-09-23-agent/'

loader=WebBaseLoader(web_path=(URL), bs_kwargs=dict(parse_only=bs4.SoupStrainer(class_=("post-title"))))
loader.load()

In [ ]:
URL= 'https://lilianweng.github.io/posts/2023-06-23-agent/'
loader=WebBaseLoader(web_path=URL, bs_kwargs=dict(parse_only=bs4.SoupStrainer(class_=("post-title"))))
loader.load()

In [ ]:
from langchain_community.document_loaders import WikipediaLoader
WikipediaLoader(query='Question')  ---> loader_obj.load() --> data
WikipediaLoader(query-'Question',load_max_docs=<count>)-> loader_obj.load()--> data

In [127]:
# ArxivLoader - research paper
from langchain_community.document_loaders import ArxivLoader
help(ArxivLoader)

Help on class ArxivLoader in module langchain_community.document_loaders.arxiv:

class ArxivLoader(langchain_core.document_loaders.base.BaseLoader)
 |  ArxivLoader(
 |      query: str,
 |      doc_content_chars_max: Optional[int] = None,
 |      **kwargs: Any
 |  )
 |
 |  Load a query result from `Arxiv`.
 |  The loader converts the original PDF format into the text.
 |
 |  Setup:
 |      Install ``arxiv`` and ``PyMuPDF`` packages.
 |      ``PyMuPDF`` transforms PDF files downloaded from the arxiv.org site
 |      into the text format.
 |
 |      .. code-block:: bash
 |
 |          pip install -U arxiv pymupdf
 |
 |
 |  Instantiate:
 |      .. code-block:: python
 |
 |          from langchain_community.document_loaders import ArxivLoader
 |
 |          loader = ArxivLoader(
 |              query="reasoning",
 |              # load_max_docs=2,
 |              # load_all_available_meta=False
 |          )
 |
 |  Load:
 |      .. code-block:: python
 |
 |          docs = loader.load()
 | 