In [1]:
import nltk

In [3]:
text=" i like to read machnine learning algorithm"

In [ ]:
LookUp Error
>>> import nltk
>>> nltk.download('punkt_tab')


In [ ]:
corpus
documents
tokens

In [4]:
from nltk.tokenize import word_tokenize
word_tokenize(text)

['i', 'like', 'to', 'read', 'machnine', 'learning', 'algorithm']

In [6]:
corpus=''' hello  welcome to Rag training .
lets learn NLP , then LLM, Chaining
Oracle 23ai, prompting '''

In [5]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize

In [7]:
print(sent_tokenize(corpus))

[' hello  welcome to Rag training .', 'lets learn NLP , then LLM, Chaining\nOracle 23ai, prompting']


In [8]:
msg="Hell0 Arun, how are you?. ok. Iam doing well. hos is activities's code "

In [9]:
word_tokenize(msg)

['Hell0',
 'Arun',
 ',',
 'how',
 'are',
 'you',
 '?',
 '.',
 'ok.',
 'Iam',
 'doing',
 'well',
 '.',
 'hos',
 'is',
 'activities',
 "'s",
 'code']

In [10]:
from nltk.tokenize import wordpunct_tokenize
wordpunct_tokenize(msg)|-

['Hell0',
 'Arun',
 ',',
 'how',
 'are',
 'you',
 '?.',
 'ok',
 '.',
 'Iam',
 'doing',
 'well',
 '.',
 'hos',
 'is',
 'activities',
 "'",
 's',
 'code']

In [ ]:
TreebankTokenizer
|
class
 |- handles apostrophies
|- split punctuation
|- adds space 

can't --> "ca"  + "n't"

In [11]:
from nltk.tokenize import wordpunct_tokenize
print(wordpunct_tokenize)

<bound method RegexpTokenizer.tokenize of WordPunctTokenizer(pattern='\\w+|[^\\w\\s]+', gaps=False, discard_empty=True, flags=re.UNICODE|re.MULTILINE|re.DOTALL)>


In [12]:
from nltk.tokenize import TreebankWordTokenizer
print(TreebankWordTokenizer)

<class 'nltk.tokenize.treebank.TreebankWordTokenizer'>


In [ ]:
nltk
|----tokenize
       |-------treebank.py
                    |
                    class TreeBankTokenizer:
                                    def tokenize(self. ):
                                         ..

In [13]:
msg

"Hell0 Arun, how are you?. ok. Iam doing well. hos is activities's code "

In [15]:
msg="Hell0 Arun, how are you?. ok. Iam doing well. how is activities's code  ab's data1.c"
from nltk.tokenize import TreebankWordTokenizer
obj=TreebankWordTokenizer()
obj.tokenize(msg)

['Hell0',
 'Arun',
 ',',
 'how',
 'are',
 'you',
 '?',
 '.',
 'ok.',
 'Iam',
 'doing',
 'well.',
 'how',
 'is',
 'activities',
 "'s",
 'code',
 'ab',
 "'s",
 'data1.c']

In [16]:
# nlp term
# Stemming - reduce to the root words

from nltk.stem import PorterStemmer
obj=PorterStemmer()
obj.stem("learning")

'learn'

In [17]:
obj.stem('history')

'histori'

In [18]:
obj.stem('congratulations')

'congratul'

In [19]:
from nltk.stem import RegexpStemmer
reg_stem = RegexpStemmer('ing$|s$|es$') # user specific regx pattern
reg_stem.stem('eating')

'eat'

In [20]:
reg_stem.stem('history')

'history'

In [ ]:
# Lemmatization - Lemma
# reducing to root word based pos = v,av,n

In [21]:
from nltk.stem import WordNetLemmatizer
lemma_obj=WordNetLemmatizer()
lemma_obj.lemmatize("eating")

'eating'

In [22]:
lemma_obj.lemmatize("eating", pos='v')

'eat'

In [23]:
lemma_obj.lemmatize("history", pos='v')

'history'

In [ ]:
StopWords - NLP reprocessing
 |------> do not carry any meaning


In [25]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\karth\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [55]:
stopwords.words('english')
#stopwords.words('arabic')
#stopwords.words('french')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
tokenization---> token - reduce this token to root word- stem-> lemma -> stopwords

In [30]:
Gn_list=["words","eats","eatern","writing",
         "writes","programming","program",
         "history","finally","finalized"]
# import nltk module
  #         |-- porterStemmer  - root words
  #      |--- WordNetLemmatizer - pos = v

In [31]:
Gn_list=["words","eats","eatern","writing",
         "writes","programming","program",
         "history","finally","finalized"]
obj=PorterStemmer()
for var in Gn_list:
    print(f'{var} ----->  {obj.stem(var)}')

words ----->  word
eats ----->  eat
eatern ----->  eatern
writing ----->  write
writes ----->  write
programming ----->  program
program ----->  program
history ----->  histori
finally ----->  final
finalized ----->  final


In [32]:
lemma_obj = WordNetLemmatizer()
for var in Gn_list:
    print(f"{var}----> { lemma_obj.lemmatize(var,pos='v')}")

words----> word
eats----> eat
eatern----> eatern
writing----> write
writes----> write
programming----> program
program----> program
history----> history
finally----> finally
finalized----> finalize


In [36]:
msg="This is an example displaying of list or collection of stop words to filter"
print(msg)

This is an example displaying of list or collection of stop words to filter


In [37]:
word_tokenize(msg)

['This',
 'is',
 'an',
 'example',
 'displaying',
 'of',
 'list',
 'or',
 'collection',
 'of',
 'stop',
 'words',
 'to',
 'filter']

In [38]:
words=word_tokenize(msg)
for var in words:
    if var.lower() not in stopwords.words('english'):
        print(var)

example
displaying
list
collection
stop
words
filter


In [39]:
filter_words= [var for var in words if var.lower() not in stopwords.words('english')]  # Functional Style- List comprehension
filter_words

['example', 'displaying', 'list', 'collection', 'stop', 'words', 'filter']

In [ ]:
#Task
#====
Corpus
|--- Use PorterStemmer  and WordNetLemmatizer()
|--- Apply StopWords
|--- Filter remaining words

In [40]:
corpus="""Vikram Sarabhai was born on 12 August 1919 in a Gujarati Śvetāmbara Shrimali Jain family, 
in Ahmedabad, India.His father was Ambalal Sarabhai,
a major industrialist committed to the Indian independence movement.
Known as the cradle of space sciences in India, the Physical Research Laboratory (PRL) was
founded in 1947 by Vikram Sarabhai. PRL had a modest beginning at his residence, the "RETREAT", 
with research on cosmic rays.
The institute was formally established at the M.G. Science Institute, Ahmedabad, on 11 November 1947 with support 
from the Karmkshetra Educational Foundation and the Ahmedabad Education Society. Kalpathi Ramakrishna Ramanathan 
was the first director of the institute. The initial focus was research on cosmic rays and the properties of the
upper atmosphere. Research areas were expanded to include theoretical physics and radio physics later
with grants from the Atomic Energy Commission. 
He led the Sarabhai family-owned business conglomerate."""

In [44]:
docs= sent_tokenize(corpus)
print(type(docs), len(docs))
for var in docs:
    print(var)

<class 'list'> 9
Vikram Sarabhai was born on 12 August 1919 in a Gujarati Śvetāmbara Shrimali Jain family, 
in Ahmedabad, India.His father was Ambalal Sarabhai,
a major industrialist committed to the Indian independence movement.
Known as the cradle of space sciences in India, the Physical Research Laboratory (PRL) was
founded in 1947 by Vikram Sarabhai.
PRL had a modest beginning at his residence, the "RETREAT", 
with research on cosmic rays.
The institute was formally established at the M.G.
Science Institute, Ahmedabad, on 11 November 1947 with support 
from the Karmkshetra Educational Foundation and the Ahmedabad Education Society.
Kalpathi Ramakrishna Ramanathan 
was the first director of the institute.
The initial focus was research on cosmic rays and the properties of the
upper atmosphere.
Research areas were expanded to include theoretical physics and radio physics later
with grants from the Atomic Energy Commission.
He led the Sarabhai family-owned business conglomerate.


In [45]:
for var in range(len(docs)):
    words= word_tokenize(docs[var])
    print(words)

['Vikram', 'Sarabhai', 'was', 'born', 'on', '12', 'August', '1919', 'in', 'a', 'Gujarati', 'Śvetāmbara', 'Shrimali', 'Jain', 'family', ',', 'in', 'Ahmedabad', ',', 'India.His', 'father', 'was', 'Ambalal', 'Sarabhai', ',', 'a', 'major', 'industrialist', 'committed', 'to', 'the', 'Indian', 'independence', 'movement', '.']
['Known', 'as', 'the', 'cradle', 'of', 'space', 'sciences', 'in', 'India', ',', 'the', 'Physical', 'Research', 'Laboratory', '(', 'PRL', ')', 'was', 'founded', 'in', '1947', 'by', 'Vikram', 'Sarabhai', '.']
['PRL', 'had', 'a', 'modest', 'beginning', 'at', 'his', 'residence', ',', 'the', '``', 'RETREAT', "''", ',', 'with', 'research', 'on', 'cosmic', 'rays', '.']
['The', 'institute', 'was', 'formally', 'established', 'at', 'the', 'M.G', '.']
['Science', 'Institute', ',', 'Ahmedabad', ',', 'on', '11', 'November', '1947', 'with', 'support', 'from', 'the', 'Karmkshetra', 'Educational', 'Foundation', 'and', 'the', 'Ahmedabad', 'Education', 'Society', '.']
['Kalpathi', 'Ramak

In [46]:
for var in range(len(docs)):
    words= word_tokenize(docs[var])
    for word in words:
        if word.lower() not in stopwords.words('english'):
            print(word.lower())

vikram
sarabhai
born
12
august
1919
gujarati
śvetāmbara
shrimali
jain
family
,
ahmedabad
,
india.his
father
ambalal
sarabhai
,
major
industrialist
committed
indian
independence
movement
.
known
cradle
space
sciences
india
,
physical
research
laboratory
(
prl
)
founded
1947
vikram
sarabhai
.
prl
modest
beginning
residence
,
``
retreat
''
,
research
cosmic
rays
.
institute
formally
established
m.g
.
science
institute
,
ahmedabad
,
11
november
1947
support
karmkshetra
educational
foundation
ahmedabad
education
society
.
kalpathi
ramakrishna
ramanathan
first
director
institute
.
initial
focus
research
cosmic
rays
properties
upper
atmosphere
.
research
areas
expanded
include
theoretical
physics
radio
physics
later
grants
atomic
energy
commission
.
led
sarabhai
family-owned
business
conglomerate
.


In [47]:
L=['data1','data2','data1','data1'] 
set(L)

{'data1', 'data2'}

In [48]:
list(set(L))

['data1', 'data2']

In [52]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

stem_obj=PorterStemmer()
docs= nltk.sent_tokenize(corpus)

for var in range(len(docs)):
    words=nltk.word_tokenize(docs[var])
    words= [stem_obj.stem(word)for word in words if word not in stopwords.words('english')]
    docs[var] =" ". join(words)

docs



['vikram sarabhai born 12 august 1919 gujarati śvetāmbara shrimali jain famili , ahmedabad , india.hi father ambal sarabhai , major industrialist commit indian independ movement .',
 'known cradl space scienc india , physic research laboratori ( prl ) found 1947 vikram sarabhai .',
 "prl modest begin resid , `` retreat '' , research cosmic ray .",
 'the institut formal establish m.g .',
 'scienc institut , ahmedabad , 11 novemb 1947 support karmkshetra educ foundat ahmedabad educ societi .',
 'kalpathi ramakrishna ramanathan first director institut .',
 'the initi focu research cosmic ray properti upper atmospher .',
 'research area expand includ theoret physic radio physic later grant atom energi commiss .',
 'he led sarabhai family-own busi conglomer .']

In [54]:
# use LEmmatization
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

lemmatizer=WordNetLemmatizer()
docs= nltk.sent_tokenize(corpus)

for var in range(len(docs)):
    words=nltk.word_tokenize(docs[var])
    words= [lemmatizer.lemmatize(word,pos="v")for word in words if word not in stopwords.words('english')]
    l=set(words)
    words=list(l)
    docs[var] =" ". join(words)

docs


[', bear major 12 . Sarabhai father Ambalal Shrimali Gujarati August Jain movement Indian Śvetāmbara independence commit family industrialist Ahmedabad India.His 1919 Vikram',
 'Sarabhai sciences space Research found Known 1947 Laboratory . Physical Vikram , ( ) PRL cradle India',
 "RETREAT `` research begin , '' residence cosmic ray modest PRL .",
 'The institute formally establish M.G .',
 'Educational 1947 support . Ahmedabad November Science Foundation Institute 11 , Society Karmkshetra Education',
 'Kalpathi institute director Ramakrishna Ramanathan first .',
 'research atmosphere upper focus The initial ray properties cosmic .',
 'Research physics theoretical include Energy areas radio later Commission grant Atomic . expand',
 'Sarabhai conglomerate business lead He family-owned .']

In [ ]:
ngram technique
===============
    An n-gram - continuous sequence of n items from a corpus

food good bad => after lemmatization and filting stopwords
n=3 => no. of unique

n=1
food --> 1 0 0 --> [1 0 0 ]
good --> 0 1 1  -> [0 1 0]
bad --> 0 0 1  ->  [ 0 0 1]


n=2
---
food good   ->  1 0
----------   
good bad    ---> 0 1

n=3
food good bad  -> 1
                  0

In [57]:
from nltk.util import ngrams


In [59]:
data="likes read nlp applications"
word_tokenize(data)

['likes', 'read', 'nlp', 'applications']

In [60]:
token= word_tokenize(data)
ngrams(token,1)  # unigram

<generator object ngrams at 0x000001EE457E9A40>

In [ ]:
>>> def f1():
...     return 10
...
>>> f1()
10
>>> def f2():
...     yield 10
...
>>> f2()
<generator object f2 at 0x0000014514D6C5F0>
>>> # function returns an iterator obj--> generator
>>>
>>> next(f2())
10
>>>
>>> for var in f2():
...     print(var)
...
10
>>> list(f2())
[10]
>>> def f3():
...     yield 10
...     yield [1,2,3]
...     yield 1,
...
>>> f3()
<generator object f3 at 0x0000014514D6DE00>
>>> next(f3())
10
>>> next(f3())
10
>>> next(f3())
10
>>> for var in f3():
...     print(var)
...
10
[1, 2, 3]
(1,)
>>> list(f3())
[10, [1, 2, 3], (1,)]
>>>

In [61]:
list(ngrams(token,1))

[('likes',), ('read',), ('nlp',), ('applications',)]

In [62]:
list(ngrams(token,2))

[('likes', 'read'), ('read', 'nlp'), ('nlp', 'applications')]

In [63]:
list(ngrams(token,3))

[('likes', 'read', 'nlp'), ('read', 'nlp', 'applications')]

In [64]:
list(ngrams(token,4))

[('likes', 'read', 'nlp', 'applications')]

In [65]:
list(ngrams(token,5))

[]

In [71]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data=['food', 'good', 'bad']

data= np.array(data).reshape(-1,1) # 2D

encoder_obj=OneHotEncoder(sparse_output=False)
one_hot=encoder_obj.fit_transform(data)
print(encoder_obj.categories_)
print('')
print(one_hot)


[array(['bad', 'food', 'good'], dtype='<U4')]

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [72]:
data=["he","widely","regards","father", "indian","space","program"]
data= np.array(data).reshape(-1,1) # 2D

encoder_obj=OneHotEncoder(sparse_output=False)
one_hot=encoder_obj.fit_transform(data)
print(encoder_obj.categories_)
print('')
print(one_hot)


[array(['father', 'he', 'indian', 'program', 'regards', 'space', 'widely'],
      dtype='<U7')]

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [ ]:
###############  BREAK 1:05 PM to 2:05PM IST  #########